flaks-config-net-dev/blueprints/net_config_device.py
from flask import Blueprint, render_template, request, redirect
from flask_login import login_required
from models import ConfigDevices, ConfigDevicesLog
from exts import db_mysql, fernet
from netmiko import ConnectHandler
import concurrent.futures
import time


bp = Blueprint("config_devices", __name__, url_prefix="/config_devices")


def config_dev(dev_ip, dev_name, dev_password, dev_vendor, dev_port, command, operation_ip):
    operation_result = ''
    try:
        if dev_vendor.lower() == 'huawei':
            sw = {'device_type': 'huawei',
                  'ip': dev_ip,
                  'username': dev_name,
                  'password': dev_password,
                  'port': dev_port}

            connect = ConnectHandler(**sw)
            huawei_output = connect.send_config_set(command)
            huawei_result = (f'----华为 {dev_ip} 上的运行结果----\n ' + huawei_output)
            operation_result = huawei_result
            connect.disconnect()

        elif dev_vendor.lower() == 'h3c':
            sw = {'device_type': 'hp_comware',
                  'ip': dev_ip,
                  'username': dev_name,
                  'password': dev_password,
                  'port': dev_port}

            connect = ConnectHandler(**sw)
            h3c_output = connect.send_config_set(command)
            h3c_result = (f'----H3C {dev_ip} 上的运行结果----\n ' + h3c_output)
            operation_result = h3c_result
            connect.disconnect()

        elif dev_vendor.lower() == 'cisco':
            sw = {'device_type': 'cisco_ios',
                  'ip': dev_ip,
                  'username': dev_name,
                  'password': dev_password,
                  'port': dev_port}
            connect = ConnectHandler(**sw)
            cisco_output = connect.send_config_set(command)
            cisco_result = (f'----Cisco {dev_ip} 上的运行结果----\n ' + cisco_output)
            operation_result = cisco_result
            connect.disconnect()
        logs = ConfigDevicesLog(target=dev_ip, remote_ip_addr=operation_ip, action='Configure', status='Success',
                                time=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), messages='No Error')

        return {'operation_log_information': operation_result,
                'writer_log': logs}

    except Exception as e:
        logs = ConfigDevicesLog(target=dev_ip, remote_ip_addr=operation_ip, action='Configure', status='Error',
                                time=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), messages=e)
        return {'operation_log_information': str(e),
                'writer_log': logs}


@bp.route("/info")
@login_required
def config_devices():
    all_device = ConfigDevices.query.all()
    context = {'all_device': all_device}
    return render_template("config_devices.html", **context)


@bp.route("/add", methods=['GET', 'POST'])
@login_required
def config_devices_add():
    vendor_choices = ["huawei", "h3c", "cisco"]
    context = {'vendor_choices': vendor_choices}
    if request.method == "GET":
        return render_template("config_devices_add.html", **context)

    elif request.method == "POST":
        ip = request.form.get("ip")
        dev_name = request.form.get("dev_name")
        username = request.form.get("username")
        password = fernet.encrypt(request.form.get("password").encode())
        dev_port = request.form.get("dev_port")
        vendor = request.form.get("vendor")

        device_1 = ConfigDevices(ip_address=ip, hostname=dev_name, username=username, password=password, ssh_port=dev_port,
                                 vendor=vendor)
        db_mysql.session.add(device_1)
        db_mysql.session.commit()
        return redirect('info')


@bp.route("/edit", methods=['GET', 'POST'])
@login_required
def config_devices_edit():
    devices_id = request.args.get("device_id")
    dev_id = ConfigDevices.query.filter_by(id=devices_id)[0]
    if request.method == "GET":
        vendor_choices = ["huawei", "h3c", "cisco"]
        context = {'dev_id': dev_id,
                   'vendor_choices': vendor_choices}
        return render_template("config_devices_edit.html", **context)

    elif request.method == "POST":
        dev_id.ip_address = request.form.get("ip")
        dev_id.hostname = request.form.get("dev_name")
        dev_id.username = request.form.get("username")
        if request.form.get("password"):
            dev_id.password = fernet.encrypt(request.form.get("password").encode())
        dev_id.ssh_port = request.form.get("dev_port")
        dev_id.vendor = request.form.get("vendor")
        db_mysql.session.commit()
        return redirect("info")


@bp.route("/delete", methods=['GET'])
@login_required
def config_devices_delete():
    if request.method == "GET":
        devices_id = request.args.get("device_id")
        print(devices_id)
        ConfigDevices.query.filter_by(id=devices_id).delete()
        db_mysql.session.commit()
        return redirect('info')


@bp.route("/config", methods=['GET', 'POST'])
@login_required
def config_devices_config():
    dev_information = list()
    web_operation_log = list()
    if request.method == "GET":
        all_device = ConfigDevices.query.all()
        context = {'all_device': all_device}
        return render_template("config_devices_config.html", **context)

    elif request.method == "POST":
        remote_ip = str(request.remote_addr)
        start_time = time.time()
        dev_list = list()
        selected_device_id = request.form.getlist("device")
        # 获取WEB页面上的命令信息
        get_huawei_command = request.form.get('huawei_command').splitlines()
        get_h3c_command = request.form.get('h3c_command').splitlines()
        get_cisco_command = request.form.get('cisco_command').splitlines()

        if selected_device_id:
            for one_device_id in selected_device_id:
                dev = ConfigDevices.query.filter_by(id=int(one_device_id))[0]
                if dev.vendor.lower() == 'huawei':
                    dev_list.append([dev.ip_address, dev.username, fernet.decrypt(dev.password.encode()), dev.vendor,
                                     dev.ssh_port, get_huawei_command, remote_ip])

                elif dev.vendor.lower() == 'h3c':
                    dev_list.append([dev.ip_address, dev.username, fernet.decrypt(dev.password.encode()), dev.vendor,
                                     dev.ssh_port, get_h3c_command, remote_ip])

                elif dev.vendor.lower() == 'cisco':
                    dev_list.append([dev.ip_address, dev.username, fernet.decrypt(dev.password.encode()), dev.vendor,
                                     dev.ssh_port, get_cisco_command, remote_ip])

            with concurrent.futures.ThreadPoolExecutor() as executor:
                futures = [executor.submit(config_dev, param[0], param[1], param[2], param[3], param[4], param[5],
                                           param[6]) for param in dev_list]
                return_value = [f.result() for f in futures]
                for one_return_value in return_value:
                    dev_information.append(one_return_value['operation_log_information'])
                    web_operation_log.append(one_return_value['writer_log'])

            dev_information.append(f'----执行时长为 {time.time() - start_time} ----\n')

            for one_web_operation_log in web_operation_log:
                db_mysql.session.add(one_web_operation_log)
                db_mysql.session.commit()

            context = {'result': '\n'.join(dev_information)}
            return render_template('config_devices_verify_config.html', **context)

        else:
            context = {'result': '请先选择需要配置的设备'}
            return render_template('config_devices_verify_config.html', **context)


@bp.route("/log")
def config_devices_log():
    page = request.args.get("page", 1)
    log_all = ConfigDevicesLog.query.paginate(page=int(page), per_page=13)
    context = {'log_all': log_all}
    return render_template("config_devices_config_log.html", **context)

flaks-config-net-dev/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>{% block hade %}  {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href={{ url_for('static', filename='css/style-index.css') }}>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
        </div>
        <div class="p-4 pt-5">
            <h1><a href="index.html" class="logo">NETdevops</a></h1>
            <ul class="list-unstyled components mb-5">
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                       class="dropdown-toggle">设备配置管理</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href={{ url_for('config_devices.config_devices') }}>配置设备信息</a>
                        </li>
                        <li>
                            <a href={{ url_for('config_devices.config_devices_config') }}>设备配置下发</a>
                        </li>
                        <li>
                            <a href={{ url_for('config_devices.config_devices_log') }}>设备配置日志</a>
                        </li>
                        </li>
                    </ul>
                </li>
            </ul>

            <!-- <div class="mb-5">
              <h3 class="h6">搜索</h3>
              <form action="#" class="colorlib-subscribe-form">
                <div class="form-group d-flex">
                  <div class="icon"><span class="icon-paper-plane"></span></div>
                  <input type="text" class="form-control" placeholder="输入你要查找的信息">
                </div>
              </form>
            </div> -->

            <div class="mb-1">
                <a type="button" class="btn btn-dark" href={{ url_for('logout') }}>LOGOUT</a>
            </div>

        </div>
    </nav>

    <!-- Page Content  -->
    <div id="content" class="p-4 p-md-5 pt-5">
        {% block content %} {% endblock %}
    </div>

</div>

</body>

<script src={{ url_for('static', filename='js/jquery.min.js') }}></script>
<script src={{ url_for('static', filename='js/bootstrap.min.js') }}></script>
<script src={{ url_for('static', filename='js/main.js') }}></script>

</html>

flaks-config-net-dev/templates/config_devices.html
{% extends "base.html" %}

{% block hade  %} 配置设备信息 {% endblock hade %}

{% block content %}
    <h2 class="mt-4">设备列表</h2>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>IP地址</th>
            <th>主机名</th>
            <th>厂商</th>
            <th>端口</th>
            <th>操作</th>
        </tr>
        {% for device in all_device %}
            <tr>
                <td>{{ device.id }}</td>
                <td>{{ device.ip_address }}</td>
                <td>{{ device.hostname }}</td>
                <td>{{ device.vendor }}</td>
                <td>{{ device.ssh_port }}</td>
                <td>
                    <a type="button" class="btn btn-warning" href="/config_devices/edit?device_id={{ device.id }}">编辑</a>
                    <a type="button" class="btn btn-danger" href="/config_devices/delete?device_id={{ device.id }}">删除</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <a class="mt-3 btn btn-primary" href="/config_devices/add">添加设备</a>
{% endblock content %}

flaks-config-net-dev/templates/config_devices_add.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> 新增加设备 </h3>
  </div>
  <div class="panel-body">
    <form method="post">
      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录地址</label>
        <div class="col-sm-10">
          <input type="text" class="form-control"  placeholder="请输ip地址或域名" name="ip">
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备名称</label>
        <div class="col-sm-10">
          <input type="text" class="form-control"  placeholder="请输设备名称" name="dev_name">
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录用户</label>
        <div class="col-sm-10">
          <input type="text" class="form-control"  placeholder="请输入设备登录用户" name="username">
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录密码</label>
        <div class="col-sm-10">
          <input type="password" class="form-control"  placeholder="请输入设备登录密码" name="password">
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录端口号</label>
        <div class="col-sm-10">
          <input type="text" class="form-control"  placeholder="22" name="dev_port" value="22">
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">请选择设备厂商</label>
        <div class="col-sm-10">
            <select class="form-control" name="vendor">
                {% for item in vendor_choices %}
                <option value="{{ item }}">{{ item }}</option>
                {% endfor %}
            </select>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn-primary btn-xs">提 交</button>
        </div>
      </div>
      </form>
  </div>
</div>
</div>

{% endblock content %}

flaks-config-net-dev/templates/config_devices_config.html
{% extends "base.html" %}

{% block hade  %} 配置设备 {% endblock hade %}

{% block content %}
<h1 class="mt-3">{{mode}}</h1>
<form method="POST">
  <h4 class="mt-5">选择要配置的设备:</h4>

  <input type="button" value="全选" id="sele"/>
  <input type="button" value="不选" id="setinterval"/>
  <input type="button" value="反选" id="clear"/>

  <div class="checkbox" id="checkboxs">
    <label>
      {% for device in all_device %}
      <input type="checkbox" class="check" name="device" value="{{ device.id }}">{{device.ip_address}} :
      {{device.hostname}} : {{device.vendor}} <br>
      {% endfor %}
    </label>
  </div>

  <h4 class="mt-3">华为设备命令</h4>
    <textarea class="form-control" name="huawei_command"></textarea>

  <h4 class="mt-3">H3C设备命令</h4>
    <textarea class="form-control" name="h3c_command"></textarea>

  <h4 class="mt-3">Cisco设备命令</h4>
    <textarea class="form-control" name="cisco_command"></textarea>

  <button type="submit" class="mt-3 btn btn-primary">提交命令</button>
</form>

{% endblock content %}

flaks-config-net-dev/templates/config_devices_config_log.html
{% extends 'base.html' %}

{% block hade  %} 设备配置日志 {% endblock hade %}

{% block content %}
<table class="table">
    <thead>
        <tr>
            <th>日志ID</th>
            <th>目标设备IP</th>
            <th>操作IP</th>
            <th>操作</th>
            <th>状态</th>
            <th>时间</th>
            <th>错误日志</th>
        </tr>
    </thead>
    <tbody>
        {% for log in log_all.items %}
        <tr>
            <td>{{log.id}}</td>
            <td>{{log.target}}</td>
            <td>{{log.remote_ip_addr}}</td>
            <td>{{log.action}}</td>
            <td>{{log.status}}</td>
            <td>{{log.time}}</td>
            <td>{{log.messages}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class={% if not log_all.has_prev %} "page-item disabled" {% endif %}>
      <a class="page-link" href="{{ url_for("config_devices.config_devices_log") }}?page={{ log_all.prev_num }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

    {% for num in range(1, log_all.pages + 1) %}
    <li {% if num == log_all.page %} class="page-item active " {% endif %}>
      <a class="page-link" href= "{{ url_for("config_devices.config_devices_log") }}?page={{ num }}"> {{ num }} </a>
    </li>
    {% endfor %}

    <li class={% if not log_all.has_next %} "page-item disabled"  {% endif %}>
      <a class="page-link" href="{{ url_for("config_devices.config_devices_log") }}?page={{ log_all.next_num }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>

{% endblock content %}

flaks-config-net-dev/templates/config_devices_edit.html
{% extends "base.html" %}

{% block hade  %} 编辑设备 {% endblock hade %}

{% block content %}

<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> 编辑设备 </h3>
  </div>
  <div class="panel-body">
    <form method="post">
      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录地址</label>
        <div class="col-sm-10">
            <label>
                <input type="text" class="form-control"  placeholder="请输ip地址或域名" name="ip" value={{ dev_id.ip_address }}>
            </label>
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备名称</label>
        <div class="col-sm-10">
            <label>
                <input type="text" class="form-control"  placeholder="请输设备名称" name="dev_name" value={{ dev_id.hostname }}>
            </label>
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录用户</label>
        <div class="col-sm-10">
            <label>
                <input type="text" class="form-control"  placeholder="请输入设备登录用户" name="username" value={{ dev_id.username }}>
            </label>
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录密码</label>
        <div class="col-sm-10">
            <label>
                <input type="password" class="form-control"  placeholder="请输入设备登录密码" name="password">
            </label>
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备登录端口号</label>
        <div class="col-sm-10">
            <label>
                <input type="text" class="form-control"  placeholder="22" name="dev_port" value={{ dev_id.ssh_port }}>
            </label>
        </div>
      </div>

      <div class="form-group">
        <label for="inputText" class="col-sm-2 control-label">设备厂商</label>
        <div class="col-sm-10">
            <label>
                <input type="text" class="form-control"  placeholder="22" name="vendor" value={{ dev_id.vendor }}>
            </label>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit"  class="btn btn-success">提 交</button>
        </div>
      </div>
      </form>
  </div>
</div>
</div>

{% endblock content %}

flaks-config-net-dev/templates/config_devices_verify_config.html
{% extends "base.html" %}

{% block hade  %} 配置结果 {% endblock hade %}

{% block content %}
<h1 class="mt-5">配置验证</h1>
<pre>{{ result }}</pre>
<a href={{ url_for('config_devices.config_devices_log') }}> -- 点击跳转至配置设备信息 -- </a>

{% endblock content %}

flaks-config-net-dev/templates/index.html
{% extends "base.html" %}

{% block hade  %} 主页 {% endblock hade %}

{% block content %} <h1> </h1>{% endblock content %}

flaks-config-net-dev/templates/login.html
<!doctype html>
<html lang="en">
<head>
  <title>Login 10</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href={{ url_for('static', filename='css/style.css') }}>

</head>
<body class="img js-fullheight" style="background-image: url({{ url_for('static', filename='images/bg.jpg') }});">
<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 text-center mb-5">
        <h2 class="heading-section"> LOGIN </h2>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-6 col-lg-4">
        <div class="login-wrap p-0">
          <h3 class="mb-4 text-center"></h3>
          <form action="#" class="signin-form" method="post">
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Username" required>
            </div>
            <div class="form-group">
              <input id="password-field" type="password" name="password" class="form-control" placeholder="Password"
                     required>
              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
              {% for message in get_flashed_messages() %}
                {{ message }}
              {% endfor %}
            </div>
            <div class="form-group">
              <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

<script src={{ url_for('static', filename='js/jquery.min.js') }}></script>
<script src={{ url_for('static', filename='js/bootstrap.min.js') }}></script>
<script src={{ url_for('static', filename='js/main.js') }}></script>

</body>
</html>